// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsForms.DataContex;

#nullable disable

namespace WindowsForms.Migrations
{
    [DbContext(typeof(CineContext))]
    partial class CineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WindowsForms.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Nombre = "Estados Unidos"
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Nombre = "Reino Unido"
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Nombre = "Alemania"
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            Nombre = "Francia"
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            Nombre = "Italia"
                        },
                        new
                        {
                            Id = 6,
                            Eliminado = false,
                            Nombre = "España"
                        },
                        new
                        {
                            Id = 7,
                            Eliminado = false,
                            Nombre = "Japón"
                        },
                        new
                        {
                            Id = 8,
                            Eliminado = false,
                            Nombre = "Canadá"
                        },
                        new
                        {
                            Id = 9,
                            Eliminado = false,
                            Nombre = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Eliminado = false,
                            Nombre = "México"
                        });
                });

            modelBuilder.Entity("WindowsForms.Models.Pelicula", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("_id")
                        .HasColumnType("longtext");

                    b.Property<double>("calificacion")
                        .HasColumnType("double");

                    b.Property<int>("duracion")
                        .HasColumnType("int");

                    b.Property<string>("portada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("PaisId");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Eliminado = false,
                            PaisId = 6,
                            _id = "1",
                            calificacion = 9.1999999999999993,
                            duracion = 175,
                            portada = "https://ejemplo.com/portadas/el_padrino.jpg",
                            titulo = "El Padrino"
                        },
                        new
                        {
                            id = 2,
                            Eliminado = false,
                            PaisId = 8,
                            _id = "2",
                            calificacion = 8.9000000000000004,
                            duracion = 154,
                            portada = "https://ejemplo.com/portadas/pulp_fiction.jpg",
                            titulo = "Pulp Fiction"
                        },
                        new
                        {
                            id = 3,
                            Eliminado = false,
                            PaisId = 6,
                            _id = "3",
                            calificacion = 8.8000000000000007,
                            duracion = 142,
                            portada = "https://ejemplo.com/portadas/forrest_gump.jpg",
                            titulo = "Forrest Gump"
                        },
                        new
                        {
                            id = 4,
                            Eliminado = false,
                            PaisId = 2,
                            _id = "4",
                            calificacion = 8.9000000000000004,
                            duracion = 195,
                            portada = "https://ejemplo.com/portadas/schindler.jpg",
                            titulo = "La lista de Schindler"
                        },
                        new
                        {
                            id = 5,
                            Eliminado = false,
                            PaisId = 6,
                            _id = "5",
                            calificacion = 8.9000000000000004,
                            duracion = 201,
                            portada = "https://ejemplo.com/portadas/lotr_rey.jpg",
                            titulo = "El Señor de los Anillos: El Retorno del Rey"
                        },
                        new
                        {
                            id = 6,
                            Eliminado = false,
                            PaisId = 6,
                            _id = "6",
                            calificacion = 8.8000000000000007,
                            duracion = 148,
                            portada = "https://ejemplo.com/portadas/inception.jpg",
                            titulo = "Inception"
                        },
                        new
                        {
                            id = 7,
                            Eliminado = false,
                            PaisId = 8,
                            _id = "7",
                            calificacion = 8.8000000000000007,
                            duracion = 139,
                            portada = "https://ejemplo.com/portadas/fight_club.jpg",
                            titulo = "Fight Club"
                        },
                        new
                        {
                            id = 8,
                            Eliminado = false,
                            PaisId = 8,
                            _id = "8",
                            calificacion = 8.5999999999999996,
                            duracion = 169,
                            portada = "https://ejemplo.com/portadas/interstellar.jpg",
                            titulo = "Interstellar"
                        },
                        new
                        {
                            id = 9,
                            Eliminado = false,
                            PaisId = 2,
                            _id = "9",
                            calificacion = 8.5,
                            duracion = 155,
                            portada = "https://ejemplo.com/portadas/gladiator.jpg",
                            titulo = "Gladiator"
                        },
                        new
                        {
                            id = 10,
                            Eliminado = false,
                            PaisId = 2,
                            _id = "10",
                            calificacion = 8.6999999999999993,
                            duracion = 136,
                            portada = "https://ejemplo.com/portadas/matrix.jpg",
                            titulo = "Matrix"
                        });
                });

            modelBuilder.Entity("WindowsForms.Models.Pelicula", b =>
                {
                    b.HasOne("WindowsForms.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");

                    b.Navigation("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
